ow Microsoft\rquote s instructions to be licensed to use the software and reactivate,\par
\pard\nowidctlpar\li720\sb120\sa120\tx720 and you may not be able to\par
\pard\nowidctlpar\fi-360\li1080\sb120\sa120\tx1080\cf1\'b7\cf0\tab use or continue to use the software or some of the features of the software, or\par
\cf1\'b7\cf0\tab obtain certain updates or upgrades from Microsoft.\par
\pard\nowidctlpar\s2\fi-363\li720\sb120\sa120\tx720\b d.\tab\b0 You may only obtain updates or upgrades for the software from Microsoft or authorized sources. For more information on obtaining updates from authorized sources see go.microsoft.com/fwlink/?Linkid=104612.\par
\pard\nowidctlpar\s1\fi-357\li357\sb120\sa120\tx360\b 8.\tab PRE-RELEASE SOFTWARE. \b0 This software is a pre-release version. It may not work the way a final version of the software will. We may change it for the final, commercial version. We also may not release a commercial version.\b\par
\pard\nowidctlpar\s1\fi-360\li360\sb120\sa120\tx360 9.\tab FEEDBACK. \b0 If you give feedback about the software to Microsoft, you give to Microsoft, without charge, the right to use, share and commercialize your feedback in any way and for any purpose. You also give to third parties, without charge, any patent rights needed for their products, technologies and services to use or interface with any specific parts of a Microsoft software or service that includes the feedback. You will not give feedback that is subject to a license that requires Microsoft to license its software or documentation to third parties because we include your feedback in them. These rights survive this agreement.\b\par
\pard\nowidctlpar\s1\fi-357\li357\sb120\sa120\tx360\caps 10.\tab Scope of License\caps0 .\b0  The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you may use the software only as expressly permitted in this agreement. In doing so, you must comply with any technical limitations in the software that only allow you to use it in certain ways. You may not\b\par
\pard\nowidctlpar\fi-363\li720\sb120\sa120\tx720\cf1\b0\'b7\cf0\tab disclose the results of any benchmark tests of the software to any third party without Microsoft\rquote s prior written approval;\par
\pard\nowidctlpar\fi-363\li720\sb120\sa120\cf1\'b7\cf0\tab work around any technical limitations in the software;\par
\cf1\'b7\cf0\tab reverse engineer, decompile or disassemble the software, except and only to the extent that applicable law expressly permits, despite this limitation;\par
\cf1\'b7\cf0\tab use components of the software to run applications not running on the software;\par
\cf1\'b7\cf0\tab make more copies of the software than specified in this agreement or allowed by applicable law, despite this limitation;\par
\cf1\'b7\cf0\tab publish the software for others to copy;\par
\cf1\'b7\cf0\tab rent, lease or lend the software;\par
\cf1\'b7\cf0\tab transfer the software or this agreement to any third party;\par
\cf1\'b7\cf0\tab use the Potentially Unwanted Software definitions separately from the software; or\par
\cf1\'b7\cf0\tab use the software for commercial software hosting services.\par
\pard\nowidctlpar\fi-360\li360\sb120\sa120\tx360\b\caps 11.\tab Notice About the H.264/AVC Visual Standard, the VC-1 Video Standard, the MPEG-4 Visual Standard and the MPEG-2 Video Standard.\b0\caps0  This software includes H.264/MPEG-4 AVC, VC-1, MPEG-4 Part 2, and MPEG-2 visual compression technology. MPEG LA, L.L.C. requires this notice:\par
\pard\nowidctlpar\li360\sb120\sa120\tx360 THIS PRODUCT IS LICENSED UNDER THE AVC, THE VC-1, THE MPEG-4 PART 2 VISUAL, AND THE MPEG-2 VIDEO PATENT PORTFOLIO LICENSES FOR THE PERSONAL AND NON-COMMERCIAL USE OF A CONSUMER TO (i) ENCODE VIDEO IN COMPLIANCE WITH THE ABOVE STANDARDS (\ldblquote VIDEO STANDARDS\rdblquote ) AND/OR (ii) DECODE AVC, VC-1, MPEG-4 PART 2 AND MPEG-2 VIDEO THAT WAS ENCODED BY A CONSUMER ENGAGED IN A PERSONAL AND NON-COMMERICAL ACTIVITY AND/OR WAS OBTAINED FROM A VIDEO PROVIDER LICENSED TO PROVIDE SUCH VIDEO. NO LICENSE IS GRANTED OR SHALL BE IMPLIED FOR ANY OTHER USE. ADDITIONAL INFORMATION MAY BE OBTAINED FROM MPEG LA, L.L.C SEE WWW.MPEGLA.COM.\par
\pard\nowidctlpar\s1\fi-357\li357\sb120\sa120\tx360\b\caps 12.\tab Export Restrictions\caps0 .\b0  The software is subject to United States export laws and regulations. You must comply with all domestic and international export laws and regulations that apply to the software. These laws include restrictions on destinations, end users and end use. For additional information, see go.microsoft.com/fwlink/?LinkId=83205.\ul\b\par
\ulnone\caps 13.\tab SUPPORT SERVICES.\caps0  \b0 Because this software is \ldblquote as is,\rdblquote  we may not provide support services for it.\b\par
\caps 14.\tab Entire Agreement.\b0\caps0  This agreement, and the terms for supplements, updates, Internet